module.exports = {
    delta: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Last delta value',
                de: 'Letzter Deltawert',
                ru: 'Последнее значение delta',
                pt: 'Último valor delta',
                nl: 'Laatste delta waarde',
                fr: 'Dernière valeur delta',
                it: 'Ultimo valore delta',
                es: 'Último valor delta',
                pl: 'Wartość delta',
                uk: 'Останнє дельта-значення',
                'zh-cn': '上次审议的价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    last: {
        common: {
            type: 'mixed',
            role: 'value',
            name: {
                en: 'Last value',
                de: 'Letzter Wert',
                ru: 'Последняя ценность',
                pt: 'Último valor',
                nl: 'Laatste waarde',
                fr: 'Dernière valeur',
                it: 'Ultimo valore',
                es: 'Último valor',
                pl: 'Wartość końcowa',
                uk: 'Останнє значення',
                'zh-cn': '最后价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    '15Min': {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: '15 minute value',
                de: '15 Minuten Wert',
                ru: '15 минутное значение',
                pt: 'valor de 15 minutos',
                nl: '15 minuten',
                fr: 'valeur de 15 minutes',
                it: 'valore di 15 minuti',
                es: 'valor de 15 minutos',
                pl: '15 minut',
                uk: 'значення 15 хвилин',
                'zh-cn': '15分钟',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    hour: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Hourly value',
                de: 'Stundenwert',
                ru: 'Почасовая стоимость',
                pt: 'Valor por hora',
                nl: 'Urly waarde',
                fr: 'Valeur horaire',
                it: 'Valore oraria',
                es: 'Valor hora',
                pl: 'Godzina',
                uk: 'Погодинна вартість',
                'zh-cn': '高价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    day: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Daily value',
                de: 'Tageswert',
                ru: 'Ежедневная стоимость',
                pt: 'Valor diário',
                nl: 'Daily waarde',
                fr: 'Valeur quotidienne',
                it: 'Valore giornaliero',
                es: 'Valor diario',
                pl: 'Daily',
                uk: 'Добова норма',
                'zh-cn': '每日价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    week: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Weekly value',
                de: 'Wöchentlicher Wert',
                ru: 'Еженедельное значение',
                pt: 'Valor semanal',
                nl: 'Weekly waarde',
                fr: 'Valeur hebdomadaire',
                it: 'Valore settimanale',
                es: 'Valor semanal',
                pl: 'Wartość tygodniowa',
                uk: 'Тижневе значення',
                'zh-cn': '周值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    month: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Monthly value',
                de: 'Monatlicher Wert',
                ru: 'Ежемесячное значение',
                pt: 'Valor mensal',
                nl: 'Maandelijk waarde',
                fr: 'Valeur mensuelle',
                it: 'Valore mensile',
                es: 'Valor mensual',
                pl: 'Monthly wartości',
                uk: 'Місячне значення',
                'zh-cn': '月值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    quarter: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Quarterly value',
                de: 'Vierteljährlicher Wert',
                ru: 'Ежеквартальное значение',
                pt: 'Valor trimestral',
                nl: 'Quarteriële waarde',
                fr: 'Valeur trimestrielle',
                it: 'Valore trimestrale',
                es: 'Valor trimestral',
                pl: 'Kwartalnik',
                uk: 'Квартальне значення',
                'zh-cn': '定量价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    year: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Yearly value',
                de: 'Jährlicher Wert',
                ru: 'Ежедневная ценность',
                pt: 'Valor anual',
                nl: 'Jarenlange waarde',
                fr: 'Valeur annuelle',
                it: 'Valore annuale',
                es: 'Valor anual',
                pl: 'Rocznik',
                uk: 'Річне значення',
                'zh-cn': '年值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    dayMax: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Daily max value',
                de: 'Tagesmaximalwert',
                ru: 'Ежедневная максимальная ценность',
                pt: 'Valor máximo diário',
                nl: 'Daily Max waarde',
                fr: 'Valeur quotidienne maximale',
                it: 'Valore massimo giornaliero',
                es: 'Valor máximo diario',
                pl: 'Codzienna wartość maksymalna',
                uk: 'Максимальне денне значення',
                'zh-cn': '日常价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    dayMin: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Daily min value',
                de: 'Tagesminimalwert',
                ru: 'Ежедневная мини-значимость',
                pt: 'Valor médio diário',
                nl: 'Daily min waarde',
                fr: 'Valeur quotidienne min',
                it: 'Valore minimo giornaliero',
                es: 'Valor diario min',
                pl: 'Czasopismo',
                uk: 'Щоденне мінімальне значення',
                'zh-cn': '日常价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    weekMax: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Weekly max value',
                de: 'Wöchentlicher Maximalwert',
                ru: 'Еженедельное максимальное значение',
                pt: 'Valor máximo semanal',
                nl: 'Weekly max waarde',
                fr: 'Valeur max hebdomadaire',
                it: 'Valore max settimanale',
                es: 'Valor máximo semanal',
                pl: 'Weekly max value (ang.)',
                uk: 'Максимальне тижневе значення',
                'zh-cn': '年元值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    weekMin: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Weekly min value',
                de: 'Wöchentlicher Minimalwert',
                ru: 'Еженедельное минное значение',
                pt: 'Valor mínimo semanal',
                nl: 'Weekly min waarde',
                fr: 'Valeur hebdomadaire min',
                it: 'Valore minimo settimanale',
                es: 'Valor semanal min',
                pl: 'Czasem',
                uk: 'Щотижневе мінімальне значення',
                'zh-cn': '周内价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    monthMax: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Monthly max value',
                de: 'Monatlicher Maximalwert',
                ru: 'Ежемесячная максимальная стоимость',
                pt: 'Valor máximo mensal',
                nl: 'Maandelijkse waarde',
                fr: 'Valeur maximale mensuelle',
                it: 'Valore massimo mensile',
                es: 'Valor máximo mensual',
                pl: 'Monthly max value',
                uk: 'Максимальне місячне значення',
                'zh-cn': '每月最高值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    monthMin: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Monthly min value',
                de: 'Monatlicher Minimalwert',
                ru: 'Ежемесячное значение мин',
                pt: 'Valor mínimo mensal',
                nl: 'Maandelijkse waarde',
                fr: 'Valeur mensuelle min',
                it: 'Valore minimo mensile',
                es: 'Valor mínimo mensual',
                pl: 'Miłość min',
                uk: 'Мінімальне місячне значення',
                'zh-cn': '月值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    quarterMax: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Quarterly max value',
                de: 'Vierteljährlicher Maximalwert',
                ru: 'Квартально макс. значение',
                pt: 'Valor máximo trimestral',
                nl: 'Quarterale max waarde',
                fr: 'Valeur maximale trimestrielle',
                it: 'Valore massimo trimestrale',
                es: 'Valor máximo trimestral',
                pl: 'Kwartalnik maksymalny',
                uk: 'Квартальне максимальне значення',
                'zh-cn': 'A. 定量的不可兑换值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    quarterMin: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Quarterly min value',
                de: 'Vierteljährlicher Minimalwert',
                ru: 'Ежеквартально min значение',
                pt: 'Valor mínimo trimestral',
                nl: 'Quarterly min waarde',
                fr: 'Valeur min trimestrielle',
                it: 'Valore minimo trimestrale',
                es: 'Valor trimestral min',
                pl: 'Kwartalnik',
                uk: 'Квартальне мінімальне значення',
                'zh-cn': '定量价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    yearMax: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Yearly max value',
                de: 'Jährlich Maximalwert',
                ru: 'Ежедневная максимальная ценность',
                pt: 'Valor máximo anual',
                nl: 'Jaarlijkse max waarde',
                fr: 'Valeur maximale annuelle',
                it: 'Valore massimo annuale',
                es: 'Valor máximo anual',
                pl: 'Maksimum max',
                uk: 'Річне максимальне значення',
                'zh-cn': '年值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    yearMin: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Yearly min value',
                de: 'Jährlicher Minimalwert',
                ru: 'Ежегодное минное значение',
                pt: 'Valor anual mínimo',
                nl: 'Jarenlang',
                fr: 'Valeur annuelle min',
                it: 'Valore minimo annuale',
                es: 'Valor anual min',
                pl: 'Rocznik bezwartościowy',
                uk: 'Річне мінімальне значення',
                'zh-cn': '年值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    absMax: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Absolute max value',
                de: 'Absoluter Maximalwert',
                ru: 'Абсолютная максимальная ценность',
                pt: 'Valor máximo absoluto',
                nl: 'Absolute max waarde',
                fr: 'Valeur maximale absolue',
                it: 'Valore massimo assoluto',
                es: 'Valor máximo absoluto',
                pl: 'Absolutna wartość maksymalna',
                uk: 'Абсолютне максимальне значення',
                'zh-cn': '溶剂价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    absMin: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Absolute min value',
                de: 'Absoluter Minimalwert',
                ru: 'Абсолютная мини-значимость',
                pt: 'Valor mínimo absoluto',
                nl: 'Absolute min waarde',
                fr: 'Valeur minimale',
                it: 'Valore minimo assoluto',
                es: 'Valor absoluto min',
                pl: 'Absolute miny',
                uk: 'Абсолютне мінімальне значення',
                'zh-cn': '注销价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    '15MinAvg': {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: '15 minute average',
                de: '15 minuten durchschnitt',
                ru: '15 минут в среднем',
                pt: 'média de 15 minutos',
                nl: '15 minuten gemiddeld',
                fr: 'moyenne de 15 minutes',
                it: 'media di 15 minuti',
                es: 'promedio de 15 minutos',
                pl: 'średnio 15 minut',
                uk: 'в середньому 15 хвилин',
                'zh-cn': '15分钟',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    '15MinCount': {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Counter of 15 minute values',
                de: 'Zähler von 15 Minuten',
                ru: 'Счетчик 15-минутных значений',
                pt: 'Contador de valores de 15 minutos',
                nl: 'Tegenover 15 minuten waarden',
                fr: 'Lutte contre les valeurs de 15 minutes',
                it: 'Contatore di valori 15 minuti',
                es: 'Contrata de valores de 15 minutos',
                pl: 'Kontrowersyjny',
                uk: 'Лічильник значень за 15 хвилин',
                'zh-cn': '反对15分钟的价值观',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    hourAvg: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Hourly average',
                de: 'Stundendurchschnitt',
                ru: 'Почасовая средняя',
                pt: 'Gráfico de temperatura',
                nl: 'Hourly gemiddeld',
                fr: 'Moyenne horaire',
                it: 'Media oraria',
                es: 'Promedio por hora',
                pl: 'Przeciętnie',
                uk: 'Середньогодинний',
                'zh-cn': '平均名誉',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    hourCount: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Counter of hourly values',
                de: 'Anzahl der Stundenwerte',
                ru: 'Счетчик часовых значений',
                pt: 'Contador de valores de hora em hora',
                nl: 'Contra van uurige waarden',
                fr: 'Lutte contre les valeurs horaires',
                it: 'Contatore dei valori orali',
                es: 'Contrata de valores por hora',
                pl: 'Kontrowersyjny',
                uk: 'Лічильник погодинних значень',
                'zh-cn': '对小时值的反对',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    dayAvg: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Daily average',
                de: 'Tagesdurchschnitt',
                ru: 'Ежедневный средний',
                pt: 'Média diária',
                nl: 'Daily gemiddelde',
                fr: 'Moyenne quotidienne',
                it: 'Media giornaliera',
                es: 'Promedio diario',
                pl: 'Przeciętny',
                uk: 'Середньоденний',
                'zh-cn': '每日平均',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    dayCount: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Counter of daily values',
                de: 'Anzahl der Tageswerte',
                ru: 'Счет ежедневного значения',
                pt: 'Contador de valores diários',
                nl: 'Tegen de dagelijkse waarden',
                fr: 'Lutte contre les valeurs quotidiennes',
                it: 'Controvalore giornaliero',
                es: 'Lucha contra los valores diarios',
                pl: 'Przeciwko codziennym wartościom',
                uk: 'Лічильник добових значень',
                'zh-cn': '反对日常价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    weekAvg: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Weekly average',
                de: 'Wöchentlicher Durchschnitt',
                ru: 'Среднее недельное',
                pt: 'Média semanal',
                nl: 'Weekly gemiddeld',
                fr: 'Moyenne hebdomadaire',
                it: 'Media settimanale',
                es: 'Promedio semanal',
                pl: 'Średnio',
                uk: 'Середнє за тиждень',
                'zh-cn': '平均数字',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    weekCount: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Counter of weekly values',
                de: 'Anzahl der Wochenwerte',
                ru: 'Счет еженедельных ценностей',
                pt: 'Contador de valores semanais',
                nl: 'Tegen de wekelijkse waarden',
                fr: 'Lutte contre les valeurs hebdomadaires',
                it: 'Contatore dei valori settimanali',
                es: 'Lucha contra los valores semanales',
                pl: 'Kontrowersyjny',
                uk: 'Лічильник тижневих значень',
                'zh-cn': '对每周价值的反对',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    monthAvg: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Monthly average',
                de: 'Monatlicher Durchschnitt',
                ru: 'Среднемесячный',
                pt: 'Média mensal',
                nl: 'Maandelijk gemiddeld',
                fr: 'Moyenne mensuelle',
                it: 'Media mensile',
                es: 'Promedio mensual',
                pl: 'Średnio',
                uk: 'Середньомісячний',
                'zh-cn': '月平均',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    monthCount: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Counter of monthly values',
                de: 'Anzahl der monatlichen Werte',
                ru: 'Счет ежемесячного значения',
                pt: 'Contador de valores mensais',
                nl: 'Contra van maandelijkse waarden',
                fr: 'Lutte contre les valeurs mensuelles',
                it: 'Contatore dei valori mensili',
                es: 'Contratación de los valores mensuales',
                pl: 'Przeciwko miesięcznym wartościom',
                uk: 'Лічильник місячних значень',
                'zh-cn': '每月价值的处理',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    quarterAvg: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Quarterly average',
                de: 'Vierteljährlicher Durchschnitt',
                ru: 'Квартальный средний',
                pt: 'Média trimestral',
                nl: 'Quarter gemiddeld',
                fr: 'Moyenne trimestrielle',
                it: 'Media trimestrale',
                es: 'Promedio trimestral',
                pl: 'Średnio',
                uk: 'Середньоквартальний',
                'zh-cn': '平均数量',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    quarterCount: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Counter of quarterly values',
                de: 'Anzahl der vierteljährlichen Werte',
                ru: 'Счетчик квартальных значений',
                pt: 'Contador de valores trimestrais',
                nl: 'Tegendeel van kwartaal waarden',
                fr: 'Lutte contre les valeurs trimestrielles',
                it: 'Controvalore trimestrale',
                es: 'Contrato de valores trimestrales',
                pl: 'Kontrowersyjny',
                uk: 'Лічильник квартальних значень',
                'zh-cn': '对季度价值的反对',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    yearAvg: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Yearly average',
                de: 'Jahresdurchschnitt',
                ru: 'Среднее',
                pt: 'Média anual',
                nl: 'Jaarlijks gemiddeld',
                fr: 'Moyenne annuelle',
                it: 'Media annuale',
                es: 'Promedio anual',
                pl: 'Średnio',
                uk: 'Середньорічне значення',
                'zh-cn': '年平均',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    yearCount: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Counter of yearly values',
                de: 'Anzahl der jährlichen Werte',
                ru: 'Счетчик годовых ценностей',
                pt: 'Contador de valores anuais',
                nl: 'Tegen de jaarlijkse waarden',
                fr: 'Lutte contre les valeurs annuelles',
                it: 'Controvalore annuale',
                es: 'Contratación de los valores anuales',
                pl: 'Kontrowersyjny',
                uk: 'Лічильник річних значень',
                'zh-cn': '反年价值',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    mean5Min: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: '5min mean value',
                de: '5min Mittelwert',
                ru: '5мин означает значение',
                pt: 'valor médio 5min',
                nl: '5 minuten',
                fr: 'valeur moyenne 5min',
                it: '5min valore medio',
                es: '5min valor medio',
                pl: 'wartość 5',
                uk: '5 хв середнє значення',
                'zh-cn': '5分钟',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    dayMax5Min: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Daily max value (5min)',
                de: 'Tagesmaximalwert (5min)',
                ru: 'Ежедневная максимальная ценность (5мин)',
                pt: 'Valor máximo diário (5min)',
                nl: 'Daily max waarde (5min)',
                fr: 'Valeur quotidienne max (5min)',
                it: 'Valore massimo giornaliero (5min)',
                es: 'Valor máximo diario (5min)',
                pl: 'Daily Maksymal (ang.)',
                uk: 'Максимальне щоденне значення (5 хв)',
                'zh-cn': '日常价值(5分钟)',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    dayMin5Min: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Daily min value (5min)',
                de: 'Tagesminimalwert (5min)',
                ru: 'Ежедневная минимальная стоимость (5мин)',
                pt: 'Valor mínimo diário (5min)',
                nl: 'Daily min waarde (5min)',
                fr: 'Valeur quotidienne min (5min)',
                it: 'Valore minimo giornaliero (5min)',
                es: 'Valor diario de min (5min)',
                pl: 'The Daily Min (ang.)',
                uk: 'Щоденне мінімальне значення (5 хв)',
                'zh-cn': '每日价值(5分钟)',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    last5Min: {
        common: {
            type: 'number',
            role: 'value',
            name: {
                en: 'Last value (5min)',
                de: 'Letzter Wert (5min)',
                ru: 'Последняя ценность (5мин)',
                pt: 'Último valor (5min)',
                nl: 'Laatste waarde (5min)',
                fr: 'Dernière valeur (5min)',
                it: 'Ultimo valore (5min)',
                es: 'Último valor (5min)',
                pl: 'Ostatnia wartość (5min)',
                uk: 'Останнє значення (5 хв)',
                'zh-cn': '最后价值(5分钟)',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    last01: {
        common: {
            type: 'number',
            role: 'value.time',
            name: {
                en: 'Last change (0 to 1)',
                de: 'Letzte Änderung (0 zu 1)',
                ru: 'Последнее изменение (0 до 1)',
                pt: 'Última mudança (0 a 1)',
                nl: 'Laatste verandering',
                fr: 'Dernier changement (0 à 1)',
                it: 'Ultimo cambiamento (0 a 1)',
                es: 'Último cambio (0 a 1)',
                pl: 'Ostatnia zmiana (od 0 do 1)',
                uk: 'Остання зміна (від 0 до 1)',
                'zh-cn': '上次变化(0至1)',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    last10: {
        common: {
            type: 'number',
            role: 'value.time',
            name: {
                en: 'Last change (1 to 0)',
                de: 'Letzte Änderung (1 zu 0)',
                ru: 'Последнее изменение (1 до 0)',
                pt: 'Última mudança (1 a 0)',
                nl: 'Laatste verandering',
                fr: 'Dernière modification (1 à 0)',
                it: 'Ultimo cambiamento (1 a 0)',
                es: 'Último cambio (1 a 0)',
                pl: 'Ostatnia zmiana (1 do 0)',
                uk: 'Остання зміна (від 1 до 0)',
                'zh-cn': '上次变化(1至0.)',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    lastPulse: {
        common: {
            type: 'boolean',
            role: 'value',
            name: {
                en: 'Last received pulse status',
                de: 'Letzter empfangener Impulsstatus',
                ru: 'Последний получил статус импульса',
                pt: 'Último estado de pulso recebido',
                nl: 'Laatst kreeg ik een hartstilstand',
                fr: 'Dernier état des impulsions',
                it: 'Ultimo stato di impulso ricevuto',
                es: 'Último estado de pulso recibido',
                pl: 'Status pulsacyjny',
                uk: 'Статус останнього отриманого пульсу',
                'zh-cn': '上次收到的情况',
            },
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    on15Min: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: '15min timer (ON)',
                de: '15min Timer (ON)',
                ru: '15мин таймер (ON)',
                pt: '15min timer (ON)',
                nl: '15min timer (ON)',
                fr: 'Temporaire 15min (ON)',
                it: '15min timer (ON)',
                es: '15min timer (ON)',
                pl: '15 min timer (ON) (ang.)',
                uk: 'Таймер на 15 хвилин (УВІМК.)',
                'zh-cn': '15分钟',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    onHour: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per hour (ON)',
                de: 'Timer pro Stunde (ON)',
                ru: 'Таймер в час (ON)',
                pt: 'Temporizador por hora (ON)',
                nl: 'Timer per uur',
                fr: 'Minuterie par heure (ON)',
                it: "Timer all'ora (ON)",
                es: 'Hora por hora (ON)',
                pl: 'Timer na godzinę (pol.)',
                uk: 'Таймер на годину (ВКЛ.)',
                'zh-cn': '小时(内罗毕办事处)',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    onDay: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per day (ON)',
                de: 'Timer pro Tag (ON)',
                ru: 'Таймер в день (ON)',
                pt: 'Temporizador por dia (ON)',
                nl: 'Timer per dag',
                fr: 'Minuterie par jour (ON)',
                it: 'Timer al giorno (ON)',
                es: 'Hora por día (ON)',
                pl: 'Timer per day (ang.)',
                uk: 'Таймер на день (ВКЛ.)',
                'zh-cn': '每天(内罗毕办事处)时间',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    onWeek: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per week (ON)',
                de: 'Timer pro Woche (ON)',
                ru: 'Таймер в неделю (ON)',
                pt: 'Temporizador por semana (ON)',
                nl: 'Timer per week',
                fr: 'Timer par semaine (ON)',
                it: 'Timer a settimana (ON)',
                es: 'Hora por semana (ON)',
                pl: 'Timer w tygodniu (ang.)',
                uk: 'Таймер на тиждень (ВКЛ.)',
                'zh-cn': '每周(内罗毕办事处)时间',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    onMonth: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per month (ON)',
                de: 'Timer pro Monat (ON)',
                ru: 'Таймер в месяц (ON)',
                pt: 'Temporizador por mês (ON)',
                nl: 'Timer per maand',
                fr: 'Minuterie par mois (ON)',
                it: 'Timer al mese (ON)',
                es: 'Horaria por mes (ON)',
                pl: 'Timer na miesiąc (ang.)',
                uk: 'Таймер на місяць (ВКЛ.)',
                'zh-cn': '每月(内罗毕办事处)时间',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    onQuarter: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per quarter (ON)',
                de: 'Timer pro Quartal (ON)',
                ru: 'Таймер на квартал (ON)',
                pt: 'Temporizador por trimestre (ON)',
                nl: 'Timer per kwartaal',
                fr: 'Timer par trimestre (ON)',
                it: 'Timer per trimestre (ON)',
                es: 'Hora por trimestre (ON)',
                pl: 'Timer na kwartał (ang.)',
                uk: 'Таймер на квартал (ВКЛ.)',
                'zh-cn': '每季度(内罗毕办事处)',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    onYear: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per year (ON)',
                de: 'Timer pro Jahr (ON)',
                ru: 'Таймер в год (ON)',
                pt: 'Temporizador por ano (ON)',
                nl: 'Timer per jaar',
                fr: 'Minuterie par an (ON)',
                it: "Timer all'anno (ON)",
                es: 'Hora por año (ON)',
                pl: 'Timer na rok (ang.)',
                uk: 'Таймер на рік (ON)',
                'zh-cn': '每年(内罗毕办事处)时间',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    off15Min: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: '15min timer (OFF)',
                de: '15min Timer (OFF)',
                ru: '15мин таймер (OFF)',
                pt: '15min timer (OFF)',
                nl: '15min timer (OFF)',
                fr: 'Temporaire de 15min (AFP)',
                it: '15min timer (OFF)',
                es: '15min timer (OFF)',
                pl: '15 min timer (OFF) (ang.)',
                uk: 'Таймер на 15 хвилин (ВИМК.)',
                'zh-cn': '15分钟',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    offHour: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per hour (OFF)',
                de: 'Timer pro Stunde (OFF)',
                ru: 'Таймер в час (OFF)',
                pt: 'Temporizador por hora (OFF)',
                nl: 'Timer per uur',
                fr: 'Minuterie par heure (OFF)',
                it: "Timer all'ora (OFF)",
                es: 'Hora por hora (OFF)',
                pl: 'Timer na godzinę (OFF) (ang.)',
                uk: 'Таймер на годину (ВИМК.)',
                'zh-cn': '每小时时间(森林论坛)',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    offDay: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per day (OFF)',
                de: 'Timer pro Tag (OFF)',
                ru: 'Таймер в день (OFF)',
                pt: 'Temporizador por dia (OFF)',
                nl: 'Timer per dag',
                fr: 'Minuterie par jour (OFF)',
                it: 'Timer al giorno (OFF)',
                es: 'Timer por día (OFF)',
                pl: 'Timer per day (ang.)',
                uk: 'Таймер на день (ВИМК.)',
                'zh-cn': '每天时间(森林论坛)',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    offWeek: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per week (OFF)',
                de: 'Timer pro Woche (OFF)',
                ru: 'Таймер в неделю (OFF)',
                pt: 'Temporizador por semana (OFF)',
                nl: 'Timer per week',
                fr: 'Timer par semaine (OFF)',
                it: 'Timer a settimana (OFF)',
                es: 'Hora por semana (OFF)',
                pl: 'Timer w tygodniu (OFF)',
                uk: 'Таймер на тиждень (ВИМК.)',
                'zh-cn': '每周时间(森林论坛)',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    offMonth: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per month (OFF)',
                de: 'Timer pro Monat (OFF)',
                ru: 'Таймер в месяц (OFF)',
                pt: 'Temporizador por mês (OFF)',
                nl: 'Timer per maand',
                fr: 'Minuterie par mois (OFF)',
                it: 'Timer al mese (OFF)',
                es: 'Horaria por mes (OFF)',
                pl: 'Timer na miesiąc (OFF) (ang.)',
                uk: 'Таймер на місяць (ВИМК.)',
                'zh-cn': '每月时间(森林论坛)',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    offQuarter: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per quarter (OFF)',
                de: 'Timer pro Quartal (OFF)',
                ru: 'Таймер на квартал (OFF)',
                pt: 'Temporizador por trimestre (OFF)',
                nl: 'Timer per kwartaal',
                fr: 'Timer par trimestre (OFF)',
                it: 'Timer per trimestre (OFF)',
                es: 'Hora por trimestre (OFF)',
                pl: 'Timer na kwartał (OFF)',
                uk: 'Таймер на квартал (ВИМК.)',
                'zh-cn': '每季度时间(森林论坛)',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
    offYear: {
        common: {
            type: 'number',
            role: 'value.interval',
            name: {
                en: 'Timer per year (OFF)',
                de: 'Timer pro Jahr (OFF)',
                ru: 'Таймер в год (OFF)',
                pt: 'Temporizador por ano (OFF)',
                nl: 'Timer per jaar',
                fr: 'Minuterie par an (OFF)',
                it: "Timer all'anno (OFF)",
                es: 'Hora por año (OFF)',
                pl: 'Timer na rok (ang.)',
                uk: 'Таймер на рік (ВИМК.)',
                'zh-cn': '每年时间(森林论坛)',
            },
            unit: 'sec',
            write: false,
            read: true,
        },
        native: {},
        type: 'state',
    },
};
